# Generated by Django 6.1 on 2026-09-01 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tranzaction_type', models.CharField(choices=[('receipt', 'Поставка'), ('write_off', 'Списание'), ('correction', 'Корректировка')], max_length=20, verbose_name='Тип операции')),
                ('quantity_changed', models.PositiveBigIntegerField(verbose_name='Количество')),
                ('document_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер накладной / Документа')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время операции')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Товар')),
            ],
        ),
    ]
