# Generated by Django 6.1 on 2026-09-01 13:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('vegetables', 'Овощи и фрукты'), ('meat', 'Мясо и птица'), ('fish', 'Рыба и морепродукты'), ('dairy', 'Молочные продукты'), ('bakery', 'Хлеб и выпечка'), ('grains', 'Крупы, макароны и бобовые'), ('oil_sauces', 'Масла и соусы'), ('canned', 'Консервы и заготовки'), ('snacks', 'Сладости и снеки'), ('drinks', 'Напитки'), ('alcohol', 'Алкогольные напитки'), ('frozen', 'Замороженные продукты'), ('spices', 'Специи и приправы'), ('baby_food', 'Детское питание'), ('healthy', 'Диетические и здоровые продукты'), ('household', 'Хозяйственные товары')], max_length=100, verbose_name='Категория продукта')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование товара')),
                ('body', models.TextField(verbose_name='Описание товара')),
                ('image', models.ImageField(upload_to='products_image/', verbose_name='Примерное фото товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(30)], verbose_name='Количество товара')),
                ('date_manufacture', models.DateField(verbose_name='Дата изготовления')),
                ('expiration_date', models.PositiveIntegerField(verbose_name='Срок годности')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Категория продукта')),
            ],
        ),
    ]
